version: "3.7"
networks:
  kong-quickstart-net:
  kong-net:

services:
  # Database
  # kong-database:
  #   image: postgres:latest
  #   container_name: kong-database
  #   environment:
  #     POSTGRES_DB: kong
  #     POSTGRES_USER: kong
  #     POSTGRES_PASSWORD: kong
  #   networks:
  #     - kong-quickstart-net
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "kong"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   restart: on-failure
  # # Kong
  kong-gateway:
    image: kong/kong-gateway:latest
    container_name: kong-gateway
    networks: 
      - kong-net
    volumes:
      - ${KONG_HOME}:/kong/declarative
    # depends_on:
      # kong-database:
      #   condition: service_healthy
    environment:
      # KONG_DATABASE: postgres
      # KONG_PG_HOST: kong-db
      # KONG_PG_USER: kong
      # KONG_PG_PASSWORD: kong
      # KONG_PG_DATABASE: kong
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_DATABASE: off
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      # KONG_LICENSE_DATA:
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure